### PR TITLE
Support for custom url path

### PR DESCRIPTION
**Pull request by radmirnovii**
Motivation:
Useful with http proxy. Previous version in `ru.yandex.clickhouse` has this feature with option USE_PATH_AS_DB=false.

current driver has WEB_CONTEXT option but it used only with trailing slash

### CODE REVIEW

**Comment by zhicwu** [comment]
Thank you @radmirnovii. Can we reuse `web_context`? I'm testing connection string with multiple hosts/URIs. Perhaps we can enhance the option to support both cases.

**Comment by zhicwu** [comment]
Thank you @radmirnovii. Can we reuse `web_context`? I'm testing connection string with multiple hosts/URIs. Perhaps we can enhance the option to support both cases.

**Comment by radmirnovii** [comment]
> Can we reuse `web_context`? 
Do you want to just remove adding trailing slash in path?

**Comment by zhicwu** [comment]
> Do you want to just remove adding trailing slash in path?

Yes. Web context should be also considered for health check like `ping`, because the url will be changed to `http://host:port/<web_context>/ping`. What's your scenario? I didn't see unit test there, so my guess was just arbitrary path without query or fragment, right?

Apologize for holding your PR for so long, I'll merge the 2 PRs with minor changes maybe, once I got load balancing performance issue fixed :<

**Comment by zhicwu** [comment]
Fixed in #956 along with some more tests.

**Pull request closed without merging**
