### PR TITLE
Added support for array of arrays at ResultSet

### PR DESCRIPTION
**Pull request by Blackmorse**
Added ability to fetch arrays of arrays from ResultSet

### CODE REVIEW

**Comment by alex-krash** [comment]
@Blackmorse , coold you, please, merge master - I will check this feature.
Thanks in advance.

**Comment by Blackmorse** [comment]
@alex-krash , I have no "write access" to merge request

**Comment by alex-krash** [comment]
@Blackmorse , I don't ask you to merge. You need to pull current master branch into yours, resolve conflicts and push your branch.

**Comment by Blackmorse** [comment]
@alex-krash ,
I've pushed it to my repository
https://github.com/Blackmorse/clickhouse-jdbc/tree/array-of-arrays-resultset-rebased

**Comment by timurib** [comment]
@Blackmorse 

The solution supports array of only 2 levels, but ClickHouse allows to go deeper, for example the command line client supports 32 :)

Another issue a bit trickier. 

The top level `ClickHouseArray::getArray` returns an array of not actual data type, but the array of `ClickHouseArray` objects, and each of them contain an array of actual data, i.e.
```java
ClickHouseArray[] data = (ClickHouseArray[]) resultSet.getArray("a").getArray();
// Long[] first = (Long[] data[0].getArray()
```
Compare it with PostgreSQL JDBC driver (it's just the first one what I checked):
```java
Long[][] array = (Long[][]) resultSet.getArray("a").getArray();
```

**Comment by Blackmorse** [comment]
@timurib,
Oh, probably I really get stuck, thinking of maximum array nesting level is 2.

About your second issue, I used alternative driver https://github.com/housepower/ClickHouse-Native-JDBC , where `ClickHouseArray::getArray`returns `ClickHouseArray`

**Comment by timurib** [comment]
> About your second issue, I used alternative driver https://github.com/housepower/ClickHouse-Native-JDBC , where `ClickHouseArray::getArray`returns `ClickHouseArray`

You are quite right, it returns `Object[]` of `ClickHouseArray` instances. 

As I understand, the documentation about [`java.sql.Array::getArray`](https://docs.oracle.com/javase/8/docs/api/java/sql/Array.html#getArray--) says that it's "implementation-defined":

>  Note: When getArray is used to materialize a base type that maps to a primitive data type, then it is implementation-defined whether the array returned is an array of that primitive data type or an array of Object.

**Comment by zhicwu** [comment]
It's been addressed in develop branch. Array of tuples etc. are supported as well.

**Pull request closed without merging**
