### PR TITLE
Tsv totals extremes 2

### PR DESCRIPTION
**Pull request by radmirnovii**
Fix for ClickHouseTabSeparatedProcessor with extremes and/or totals.

### CODE REVIEW

**Comment by zhicwu** [comment]
Thanks for your contribution @radmirnovii. That was indeed a missing feature. Will you also consider RowBinary processor?

By the way, the build break is irrelevant. It's caused by ClickHouse server, which was reported in #906. I'll enhance corresponding integration test as a workaround.

**Comment by zhicwu** [comment]
> Is it possible without parsing query?

Maybe not ;) Would be nice if we can support both formats.

Anyway, do you have time for additional changes? If not, I'll follow up to add test along with a few more changes to get it merged.

**Comment by radmirnovii** [comment]
> Anyway, do you have time for additional changes? 
There is no empty spaces or any special values. Cannot find solution without query parsing. 
But i can add support for grpc version.

**Review by zhicwu — CHANGES_REQUESTED** [review]

**Comment by zhicwu** [comment]
Sorry I think it's better to revisit this in 0.3.3 release, mainly for 3 reasons:
1. it's a bit tricky for user to call the new methods to get totals and extremes - they have to know how many rows returned from the server first, and then call them in sequence right after reading the last row
2. we'd better leverage progress stats for a more generic implementation for all protocols and formats
3. unit tests and integration tests to prove the function works well

**Pull request closed without merging**
