### PR TITLE
Rounding

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
I have faced with a problem of getting BigDecimal values from  ResultSet:
```java
resultSet.getBigDecimal("avg")
```
For example you can set the **avg**  value = 1.333334 to a cloumn
```sql
`abg` Float64
```

And when you will try to get it you will have the next exception:
```java
java.lang.ArithmeticException: Rounding necessary

	at java.base/java.math.BigDecimal.commonNeedIncrement(BigDecimal.java:4621)
	at java.base/java.math.BigDecimal.needIncrement(BigDecimal.java:4677)
	at java.base/java.math.BigDecimal.divideAndRound(BigDecimal.java:4585)
	at java.base/java.math.BigDecimal.setScale(BigDecimal.java:2891)
	at java.base/java.math.BigDecimal.setScale(BigDecimal.java:2951)
	at com.clickhouse.client.data.ClickHouseDoubleValue.asBigDecimal(ClickHouseDoubleValue.java:140)
	at com.clickhouse.client.ClickHouseValue.asBigDecimal(ClickHouseValue.java:234)
	at com.clickhouse.jdbc.ClickHouseResultSet.getBigDecimal(ClickHouseResultSet.java:237)
```

I added `RoundingMode` in order to handle decimal values

### CODE REVIEW

**Comment by zhicwu** [comment]
Thank you @volodya-lombrozo for the pull request. I changed the merge target from master to develop, and I'll merge it after double checking the rounding mode.

**Comment by zhicwu** [comment]
@volodya-lombrozo, I hope you don't mind that I changed RoundingMode to DOWN for consistency with server. Also I removed the check for NaN and Infinite because BigDecimal does not support them.

I'm going to release patch7 24 hours later - let me know if you have any concern for the changes.

**Comment by volodya-lombrozo** [comment]
Ok, thank you, @zhicwu. Everything fine, but can I ask you, why you decided to use exactly `RoundingMode.DOWN`?  \
For example in [that line](https://github.com/volodya-lombrozo/clickhouse-jdbc/blob/13e98e27fbdceff2f0dc96421036d55ce307f4df/clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/response/ClickHouseResultSet.java#L789) you use `RoundingMode.HALF_UP`.
Maybe it makes sense to create a global setting like `DEFAULT_ROUNDING_MODE` and use it everywhere?

**Comment by zhicwu** [comment]
> why you decided to use exactly `RoundingMode.DOWN`?

Just trying to make it consistency with server side implementation - see [here](https://github.com/ClickHouse/clickhouse-jdbc/pull/864/files#diff-b3c7bb9f2b5c1d2674475e3486ccedc810c3416cc320773d5f00ea29bc9d2e3aR85).

> For example in [that line](https://github.com/volodya-lombrozo/clickhouse-jdbc/blob/13e98e27fbdceff2f0dc96421036d55ce307f4df/clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/response/ClickHouseResultSet.java#L789) you use `RoundingMode.HALF_UP`.

It's legacy driver and it will be removed in 0.4.0 so I didn't change the logic this time.

> Maybe it makes sense to create a global setting like `DEFAULT_ROUNDING_MODE` and use it everywhere?

Yes. I thought about adding new default into `ClickHouseDefaults` but maybe better do that in a feature release like v0.3.3? Will create a separate PR for this.

**Comment by volodya-lombrozo** [comment]
Thank you for your answer. Now it's clear.
Yes, I think it's much better to add the new default into  `ClickHouseDefaults` in a separate PR.

**Pull request merged**
