### PR TITLE
Fix wrong precision

### PR DESCRIPTION
**Pull request by tangjiangling**
Fixes: #807 

`com.clickhouse.jdbc.ClickHouseDatabaseMetaData#getColumns`
returns the wrong precision, which is against the JDBC standard.

### CODE REVIEW

**Comment by tangjiangling** [comment]
A related issue(https://github.com/trinodb/trino/issues/10541)

**Comment by tangjiangling** [comment]
cc: @ebyhr @hashhar

**Comment by tangjiangling** [comment]
The second commit describes:
> In method `com.clickhouse.jdbc.ClickHouseDatabaseMetaData#getColumns`, 
we should map `DECIMAL_DIGITS` and `CHAR_OCTET_LENGTH` to `int32(0)`, 
otherwise it will lead to incorrect results.

Why?

The original implementation maps `DECIMAL_DIGITS` and `CHAR_OCTET_LENGTH` to `int32(null)`, which causes the corresponding field type to become `com.clickhouse.client.data.ClickHouseEmptyValue`, which is unable to update the new value, so it will end up with the wrong result.

**Comment by zhicwu** [comment]
Thanks @tangjiangling for the pull request :) I don't mind to create another patch release, but I'll need to run integration test against trino to see if there's more issues.

**Comment by tangjiangling** [comment]
> would you mind to sign CLA and rebase?

signed.

**Comment by tangjiangling** [comment]
> would you mind to sign CLA and rebase?

Sorry, I forgot to set the email, I will do that soon.

**Comment by tangjiangling** [comment]
> Sorry, I forgot to set the email, I will do that soon.

done.

**Comment by zhicwu** [comment]
> Is it a combination of all the "Merge pull request ClickHouse#..." into a single commit?

Yes, squash may work too.

>  incorrect precision

I think we should consider both cases. When the column is numeric, we use `column.getPrecision()`, otherwise fall back to `column.getDataType().getByteLength()`. Make sense?

> changed `toInt32(null)` to `toInt32(0)`

I'll need to look into this tonight and add some more tests accordingly.

**Comment by tangjiangling** [comment]
> I think we should consider both cases. When the column is numeric, we use column.getPrecision(), otherwise fall back to column.getDataType().getByteLength(). Make sense?

+1

**Comment by tangjiangling** [comment]
> +1, I will update the current PR later this evening.

I fixed it on the basis of this https://github.com/ClickHouse/clickhouse-jdbc/pull/815 .

**Comment by tangjiangling** [comment]
Fixed by #815. Now we can close this.

**Pull request closed without merging**
