### PR TITLE
Fix miscalculate nanos when format Timestamp

### PR DESCRIPTION
**Pull request by fandylua**
Fix miscalculate nanos when format Timestamp

### CODE REVIEW

**Comment by zhicwu** [comment]
Thanks for the pull request. The legacy driver does not handle DateTime* and time zone well. Also it has serious performance issue(see below comparison). Why not upgrade to 0.3.2 and use the new driver instead?

image

**Comment by fandylua** [comment]
> Thanks for the pull request. The legacy driver does not handle DateTime* and time zone well. Also it has serious performance issue(see below comparison). Why not upgrade to 0.3.2 and use the new driver instead?

Hi, I had upgraded to 0.3.2 now, but  when I use new driver to insert data to clickhouse(DateTime64(3)). 
example,  2022-02-21 13:34:16.344, I prefer to get 2022-02-21 13:34:16.344 in clickhouse but the data is  2022-02-21 13:34:16.000. the nacos has been auto ignored . 
 how can I insert time with nacos ?

**Comment by zhicwu** [comment]
Could you share the code snippet? Like the insert statement and Java code using Statement/PreparedStatement for the insertion? You may also check test at [here](https://github.com/ClickHouse/clickhouse-jdbc/blob/develop/clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java#L282).

**Comment by fandylua** [comment]
> Could you share the code snippet? Like the insert statement and Java code using Statement/PreparedStatement for the insertion? You may also check test at [here](https://github.com/ClickHouse/clickhouse-jdbc/blob/develop/clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java#L282).

dbtype  DateTime64(3)

ps set like this
``` java
ps.setTimestamp(2, new Timestamp(value / 1000L));
ps.setTimestamp(2, new Timestamp(value / 1000L));
ps.setDate(2,new Date());
ps.setObject(LocalDateTime.ofInstant(i, conn.getServerTimeZone().toZoneId()));
```

total code
``` java
            ClickHouseStatement s = conn.createStatement();) {
            s.execute("drop table if exists test_issue_612;"
                + "CREATE TABLE IF NOT EXISTS test_issue_612 (id UUID, date DateTime64(3)) ENGINE = MergeTree() ORDER BY (id, date)");
            UUID id = UUID.randomUUID();
            long value = 1617359745321000L;
            Instant i = Instant.ofEpochMilli(value / 1000L);
            LocalDateTime dt = LocalDateTime.ofInstant(i, conn.getServerTimeZone().toZoneId());
            try (PreparedStatement ps = conn.prepareStatement("insert into test_issue_612 values(?,?)")) {
                ps.setObject(1, UUID.randomUUID());
                ps.setTimestamp(2, new Timestamp(value / 1000L));
                ps.executeUpdate();
            }
```

**Comment by zhicwu** [comment]
@fandylua, please make sure you're using the new driver `com.clickhouse.jdbc.ClickHouseDriver`. Moreover, please consider to use `LocalDateTime`/`OffsetDateTime` instead of `Timestamp`, not only because the former one is recommended for processing date time values by JDBC, but also better performance - could be 10x times faster as I observed.

Anyway, below is the new test case I added and it's working well:
```java
@Test(groups = "integration")
public void testReadWriteDateTimeWithNanos() throws SQLException {
    try (ClickHouseConnection conn = newConnection(new Properties());
            Statement stmt = conn.createStatement()) {
        stmt.execute("drop table if exists test_read_write_datetime_nanos;"
                + "CREATE TABLE test_read_write_datetime_nanos (id UUID, date DateTime64(3)) ENGINE = MergeTree() ORDER BY (id, date)");
        UUID id = UUID.randomUUID();
        long value = 1617359745321000L;
        Instant i = Instant.ofEpochMilli(value / 1000L);
        LocalDateTime dt = LocalDateTime.ofInstant(i, conn.getServerTimeZone().toZoneId());
        try (PreparedStatement ps = conn
                .prepareStatement("insert into test_read_write_datetime_nanos values(?,?)")) {
            ps.setObject(1, id);
            ps.setObject(2, dt);
            // below works too but too slow
            // ps.setTimestamp(2, new Timestamp(value / 1000L));
            ps.executeUpdate();
        }

        ResultSet rs = stmt.executeQuery("select * from test_read_write_datetime_nanos");
        Assert.assertTrue(rs.next());
        Assert.assertEquals(rs.getObject(1), id);
        Assert.assertEquals(rs.getObject(2), dt);
        // rs.getString(2) will return "2021-04-02 03:35:45.321"
        Assert.assertFalse(rs.next());
    }
}
```

**Comment by zhicwu** [comment]
Close as I'm not going to merge the pull request. Please feel free to create an issue if it's still not working for you.

**Pull request closed without merging**
